eos-update-flatpak-repos: migrate Hack apps
endlessm/eos-boot-helper pull request #324
Opened 2020-11-19 21:41 UTC by erikos

We retire the Hack flatpaks in the eos-apps repository and use the Flathub one instead.

2020-11-19 21:41 UTC, erikos commented
The apps currently are in beta on Flathub, they need to be released first.

2020-11-20 10:33 UTC, wjt requested changes
Looking at what's installed on my system, what about:

- `com.hack_computer.Clippy.Extension` – I think the hope is that migrating Clubhouse will migrate this since it is an extension of Clubhouse
- `com.hack_computer.ProjectLibrary` – does this stay on eos-apps for the time being?

2020-11-20 10:33 UTC, wjt commented on eos-update-flatpak-repos
> +        "new-name": "com.hack_computer.Clubhouse",
I don't _think_ that `new-name` is needed if the names are the same. and when I run this, I get:

```
WARNING:root:Avoiding undefined behaviour, cannot rename an app with extensions: com.hack_computer.Clubhouse
```

So I think you need:

```suggestion
```

2020-11-20 10:33 UTC, wjt commented on eos-update-flatpak-repos
> +        "new-name": "com.hack_computer.OperatingSystemApp",
```suggestion
```

2020-11-20 10:33 UTC, wjt commented on eos-update-flatpak-repos
> +        "new-name": "com.hack_computer.Sidetrack",
```suggestion
```

2020-11-20 10:33 UTC, wjt commented
(Marked as draft because of the flathub beta → stable thing.)

2020-11-20 15:02 UTC, erikos commented
> Looking at what's installed on my system, what about:
> 
> * `com.hack_computer.Clippy.Extension` – I think the hope is that migrating Clubhouse will migrate this since it is an extension of Clubhouse

Correct. Or do we explicitly have to state that the Clippy extension should be now pulled from flathub instead of eos-apps?

> * `com.hack_computer.ProjectLibrary` – does this stay on eos-apps for the time being?

Deprecated. Long story: the ProjectLibrary app is deprecated, the content has been moved into the Clubhouse directly because the app depends on the SDK and getting that into Flathub is...and we do not want to continue creating our own content anyhow

2020-11-20 15:09 UTC, wjt commented
> > Looking at what's installed on my system, what about:
> > 
> > * `com.hack_computer.Clippy.Extension` – I think the hope is that migrating Clubhouse will migrate this since it is an extension of Clubhouse
> 
> Correct. Or do we explicitly have to state that the Clippy extension should be now pulled from flathub instead of eos-apps?

I think it will work as expected if you remove `new-name` from all these.

2020-11-20 15:15 UTC, wjt commented
but having said that, I'm not so sure:

```
INFO:root:Found eos-apps:app/com.hack_computer.Clubhouse/x86_64/eos3 to migrate to flathub:app/com.hack_computer.Clubhouse/x86_64/stable
INFO:root:Copying OSTree ref eos-apps:app/com.hack_computer.Clubhouse/x86_64/eos3 [9212a9287f751c8d124c8e27b17040106d5769a2c8b1dba94876a4b372ef9a63] to flathub:app/com.hack_computer.Clubhouse/x86_64/stable
ERROR:root:Failure applying migration to com.hack_computer.Clubhouse
Traceback (most recent call last):
  File "./eos-update-flatpak-repos", line 1734, in _migrate_installed_flatpaks
    repo.prepare_transaction()
gi.repository.GLib.GError: g-io-error-quark: mkdirat: Permission denied (14)
INFO:root:Found eos-apps:runtime/com.hack_computer.Clubhouse.Locale/x86_64/eos3 to migrate to flathub:app/com.hack_computer.Clubhouse.Locale/x86_64/stable
INFO:root:Copying OSTree ref eos-apps:runtime/com.hack_computer.Clubhouse.Locale/x86_64/eos3 [d79254359cc05394a5d104b7b757e097077dcc4ac3b080445eff00df1296dc26] to flathub:app/com.hack_computer.Clubhouse.Locale/x86_64/stable
ERROR:root:Failure applying migration to com.hack_computer.Clubhouse.Locale
Traceback (most recent call last):
  File "./eos-update-flatpak-repos", line 1734, in _migrate_installed_flatpaks
    repo.prepare_transaction()
gi.repository.GLib.GError: g-io-error-quark: mkdirat: Permission denied (14)
INFO:root:Found eos-apps:app/com.hack_computer.OperatingSystemApp/x86_64/eos3 to migrate to flathub:app/com.hack_computer.OperatingSystemApp/x86_64/stable
INFO:root:Copying OSTree ref eos-apps:app/com.hack_computer.OperatingSystemApp/x86_64/eos3 [439a1a8728a6275ab96a811ae3d4ece0deeeec0ea1f1ae79e564cb0730cba068] to flathub:app/com.hack_computer.OperatingSystemApp/x86_64/stable
ERROR:root:Failure applying migration to com.hack_computer.OperatingSystemApp
Traceback (most recent call last):
  File "./eos-update-flatpak-repos", line 1734, in _migrate_installed_flatpaks
    repo.prepare_transaction()
gi.repository.GLib.GError: g-io-error-quark: mkdirat: Permission denied (14)
INFO:root:Found eos-apps:app/com.hack_computer.Sidetrack/x86_64/eos3 to migrate to flathub:app/com.hack_computer.Sidetrack/x86_64/stable
INFO:root:Copying OSTree ref eos-apps:app/com.hack_computer.Sidetrack/x86_64/eos3 [3cd0eaa3793c8b876c3ca478f2938f67458632eaf0f1d50f00a0384de2693c5f] to flathub:app/com.hack_computer.Sidetrack/x86_64/stable
ERROR:root:Failure applying migration to com.hack_computer.Sidetrack
Traceback (most recent call last):
  File "./eos-update-flatpak-repos", line 1734, in _migrate_installed_flatpaks
    repo.prepare_transaction()
gi.repository.GLib.GError: g-io-error-quark: mkdirat: Permission denied (14)
```

Notice that it tries to migrate `com.hack_computer.Clubhouse.Locale` but not Clippy. (I ran as my normal user so that it didn't actually perform the migration.)

2020-11-24 13:50 UTC, wjt requested changes
Yes, you need to add Clippy explicitly. Apps' extensions are matched not by clever Flatpak means but by prefix matching:

https://github.com/endlessm/eos-boot-helper/blob/4be4d6b57df993abfbfa973943ff6cd32fea0492/eos-update-flatpak-repos#L1666-L1680

2020-11-27 19:24 UTC, erikos commented
I have added the Clippy.Extension.

The Hack apps are now available on Flathub/stable, so this can go in.

2020-11-27 19:33 UTC, andrunko approved these changes
LGTM.

2020-11-27 19:35 UTC, merged